# Generated by Django 3.1.14 on 2022-08-01 05:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.registration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.product')),
            ],
        ),
    ]
