# Generated by Django 3.1.14 on 2022-08-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
