# Generated by Django 3.1.14 on 2022-08-01 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=220)),
                ('mobile_no', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 1, 12, 0, 36, 996993))),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.registration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.product')),
            ],
        ),
    ]
